apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: term-of-user-get-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: term-of-user-get-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /term/signed
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /term/signed
