apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: route-get-signed-term
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-signed-term
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /signed_term
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /signed_term
